# Generated by Django 6.0.2 on 2026-03-14 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments_gategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_department', models.CharField(unique=True)),
                ('Short_code_department', models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.TextField()),
                ('File', models.FileField(upload_to='Summary_Bank_file/')),
                ('Level', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)])),
                ('Course', models.CharField(choices=[('Course_1', 'Course 1'), ('Course_2', 'Course 2')])),
                ('Departments', models.ManyToManyField(to='Summary_Bank.departments_gategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
