# Generated by Django 6.0.2 on 2026-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary_Bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary_bank',
            name='Publish',
            field=models.BooleanField(default=False),
        ),
    ]
