# Generated by Django 6.0.2 on 2026-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary_Bank', '0003_alter_summary_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_bank',
            name='Course',
            field=models.CharField(choices=[('1', 'Course 1'), ('2', 'Course 2')]),
        ),
    ]
