# Generated by Django 6.0.2 on 2026-03-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summary_Bank', '0004_alter_summary_bank_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_bank',
            name='Course',
            field=models.CharField(choices=[('1', '1'), ('2', '2')]),
        ),
    ]
