# Generated by Django 6.0.2 on 2026-03-06 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Profile_image', models.ImageField(default='profile_images/defuld.jpg', upload_to='profile_images/')),
                ('Bio', models.TextField(blank=True, default='', max_length=250)),
                ('Verified', models.BooleanField(default=False)),
                ('Activ', models.BooleanField(default=False)),
                ('Email_code', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
