# Generated by Django 6.0.2 on 2026-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Email_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
